services:
  - type: web
    name: tattoo-backend-api
    env: node
    region: oregon
    plan: free

    rootDir: mi-backend
    buildCommand: npm install --include=dev && npx nest build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
