services:
  - type: web
    name: tattoo-backend-api
    env: node
    region: oregon
    plan: free
    rootDir: mi-backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: tattoo-backend-api
          property: port
    autoDeploy: true
